name: Lint Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_data: |
            extends: default

            rules:
              document-start: disable
              truthy: disable
              line-length: disable
              comments: disable
